"""delete necessarily car id

Revision ID: ba3060ae64d0
Revises: e7342034ef2f
Create Date: 2023-04-29 22:11:44.451692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba3060ae64d0'
down_revision = 'e7342034ef2f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'car',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'car',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
