"""fix refresh model

Revision ID: ce0d8b627560
Revises: fa9d1712b8b4
Create Date: 2023-06-14 14:57:24.000158

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ce0d8b627560'
down_revision = 'fa9d1712b8b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
