version: '3.8'

services:
  backend:
    # image: digitalspaghetti/poputka-backend:latest
    build:
      context: ../
    container_name: backend
    restart: always
    env_file:
      - ../.env
    depends_on: 
      - db
    command: ["/app/deploy/app.sh"]
    networks:
      - postgres

  db:
    image: postgres:13.0-alpine
    container_name: db
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ../.env
    networks:
      - postgres
    ports:
      - "5432:5432"
    
  frontend:
    image: digitalspaghetti/poputka-frontend:latest
    container_name: frontend
    restart: always
    networks:
      - postgres

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - postgres

  redis:
    image: redis:7-alpine
    container_name: redis_poputka
    env_file:
      - ../.env
    restart: always


networks:
  postgres:
    driver: bridge

volumes:
  db_value:
  pgadmin: