version: '3.8'

services:
  backend:
    # image: digitalspaghetti/poputka-backend:latest
    build:
      context: ../
    container_name: backend
    restart: always
    env_file:
      - ../.env
    depends_on: 
      - db
    command: ["/app/deploy/app.sh"]
    networks:
      - postgres

  db:
    image: postgres:13.0-alpine
    container_name: db
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    networks:
      - postgres

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - postgres
  
  pgadmin:
    container_name: pgadmin-poputka
    restart: always
    image: dpage/pgadmin4
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    env_file:
      - ../.env
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    platform: linux/arm64

  redis:
    image: redis:7.2-rc2-alpine
    container_name: redis_poputka
    env_file:
      - ../.env
    restart: always
    ports:
      - '6379:6379'





networks:
  postgres:
    driver: bridge

volumes:
  db_value:
  pgadmin: