version: '3.8'

services:
  backend:
    # image: digitalspaghetti/poputka-backend:latest
    build:
      context: ../
    container_name: backend
    restart: always
    env_file:
      - ../.env
    depends_on: 
      - db
      - redis
    command: ["/app/deploy/app.sh"]

  db:
    image: postgres
    container_name: db
    env_file:
      - ../.env
    ports:
      - "5432:5432"

  # frontend:
  #   image: digitalspaghetti/poputka-frontend:latest
  #   # build:
  #     # context: ../frontend
  #   container_name: frontend
  #   restart: always

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  redis:
    image: redis
    container_name: redis_poputka
    env_file:
      - ../.env
    restart: always
  
  celery:
    build:
      context: ../
    user: nobody
    container_name: celery_poputka
    env_file:
      - ../.env
    command: sh -c "celery --app=app.tasks.celery:celery worker -l INFO"
    depends_on:
      - redis

  flower:
    build:
      context: ../
    container_name: flower_poputka
    env_file:
      - ../.env
    command: sh -c "celery --broker=redis://redis:6379/ --app=app.tasks.celery:celery flower --url_prefix=flower"

    depends_on:
      - redis
      - celery
  
  pgadmin:
    container_name: pgadmin-poputka
    restart: always
    image: dpage/pgadmin4
    depends_on:
      - db
    env_file:
      - ../.env
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    platform: linux/amd64
  

volumes:
  pgadmin:
