version: '3.8'

services:
  backend:
    build:
      context: ../
    container_name: backend
    restart: always
    env_file:
      - ../.env
    depends_on: 
      - db

  db:
    image: postgres:13.0-alpine
    container_name: db
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ../.env
    ports:
      - "5432:5432"

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - backend

volumes:
  db_value: